Title: "StARS: Study of Autism Risk in Siblings"
description: "StARS: Study of Autism Risk in Siblings"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_social: true          # show site description and social links in the footer
show_excerpts: false       # show article excerpts on the home page
show_frame: false          # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header

# collections
collections:
  authors:
    output: true
  resources:
    output: true

# default layouts
defaults:
  -
    scope:
      path: ""
      type: "resources"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - 
    scope: 
      path: ""
      type: "posts"
    values:
        layout: "post"

# categories for authors page
categories-order:
 - Paper
 - Grant
 - Talk
 - Poster
 - News

navigation:
  - {file: "people.md"}
  - {file: "research.md"}
  - {file: "participate.md"}
  - {file: "resources.md"}


external:                  # see http://fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:childlanglab@sas.upenn.edu"}
  - {title: Phone, icon: phone, url: "323-209-5081"}
  - {title: Subscribe, icon: rss, url: "https://https://www.chla.org/research/levitt-laboratory"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
